// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol.proto

package com.jq.seriliza.probuf;

public final class ProtocalWrap {
  private ProtocalWrap() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code com.jq.seriliza.probuf.packageType}
   */
  public enum packageType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>RES = 1;</code>
     */
    RES(1),
    /**
     * <code>REQ = 2;</code>
     */
    REQ(2),
    ;

    /**
     * <code>RES = 1;</code>
     */
    public static final int RES_VALUE = 1;
    /**
     * <code>REQ = 2;</code>
     */
    public static final int REQ_VALUE = 2;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static packageType valueOf(int value) {
      return forNumber(value);
    }

    public static packageType forNumber(int value) {
      switch (value) {
        case 1: return RES;
        case 2: return REQ;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<packageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        packageType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<packageType>() {
            public packageType findValueByNumber(int number) {
              return packageType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return ProtocalWrap.getDescriptor().getEnumTypes().get(0);
    }

    private static final packageType[] VALUES = values();

    public static packageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private packageType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.jq.seriliza.probuf.packageType)
  }

  public interface MessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.jq.seriliza.probuf.Message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *data_type
     * </pre>
     *
     * <code>required .com.jq.seriliza.probuf.packageType type = 1;</code>
     */
    boolean hasType();
    /**
     * <pre>
     *data_type
     * </pre>
     *
     * <code>required .com.jq.seriliza.probuf.packageType type = 1;</code>
     */
    ProtocalWrap.packageType getType();

    /**
     * <code>optional .com.jq.seriliza.probuf.Req req = 2;</code>
     */
    boolean hasReq();
    /**
     * <code>optional .com.jq.seriliza.probuf.Req req = 2;</code>
     */
    ProtocalWrap.Req getReq();
    /**
     * <code>optional .com.jq.seriliza.probuf.Req req = 2;</code>
     */
    ProtocalWrap.ReqOrBuilder getReqOrBuilder();

    /**
     * <code>optional .com.jq.seriliza.probuf.Res res = 3;</code>
     */
    boolean hasRes();
    /**
     * <code>optional .com.jq.seriliza.probuf.Res res = 3;</code>
     */
    ProtocalWrap.Res getRes();
    /**
     * <code>optional .com.jq.seriliza.probuf.Res res = 3;</code>
     */
    ProtocalWrap.ResOrBuilder getResOrBuilder();

    public ProtocalWrap.Message.PackCase getPackCase();
  }
  /**
   * <pre>
   *MyMessage
   * </pre>
   *
   * Protobuf type {@code com.jq.seriliza.probuf.Message}
   */
  public  static final class Message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.jq.seriliza.probuf.Message)
      MessageOrBuilder {
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Message() {
      type_ = 1;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              ProtocalWrap.packageType value = ProtocalWrap.packageType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = rawValue;
              }
              break;
            }
            case 18: {
              ProtocalWrap.Req.Builder subBuilder = null;
              if (packCase_ == 2) {
                subBuilder = ((ProtocalWrap.Req) pack_).toBuilder();
              }
              pack_ =
                  input.readMessage(ProtocalWrap.Req.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((ProtocalWrap.Req) pack_);
                pack_ = subBuilder.buildPartial();
              }
              packCase_ = 2;
              break;
            }
            case 26: {
              ProtocalWrap.Res.Builder subBuilder = null;
              if (packCase_ == 3) {
                subBuilder = ((ProtocalWrap.Res) pack_).toBuilder();
              }
              pack_ =
                  input.readMessage(ProtocalWrap.Res.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((ProtocalWrap.Res) pack_);
                pack_ = subBuilder.buildPartial();
              }
              packCase_ = 3;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtocalWrap.internal_static_com_jq_seriliza_probuf_Message_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtocalWrap.internal_static_com_jq_seriliza_probuf_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProtocalWrap.Message.class, ProtocalWrap.Message.Builder.class);
    }

    private int bitField0_;
    private int packCase_ = 0;
    private Object pack_;
    public enum PackCase
        implements com.google.protobuf.Internal.EnumLite {
      REQ(2),
      RES(3),
      PACK_NOT_SET(0);
      private final int value;
      private PackCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static PackCase valueOf(int value) {
        return forNumber(value);
      }

      public static PackCase forNumber(int value) {
        switch (value) {
          case 2: return REQ;
          case 3: return RES;
          case 0: return PACK_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public PackCase
    getPackCase() {
      return PackCase.forNumber(
          packCase_);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <pre>
     *data_type
     * </pre>
     *
     * <code>required .com.jq.seriliza.probuf.packageType type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *data_type
     * </pre>
     *
     * <code>required .com.jq.seriliza.probuf.packageType type = 1;</code>
     */
    public ProtocalWrap.packageType getType() {
      ProtocalWrap.packageType result = ProtocalWrap.packageType.valueOf(type_);
      return result == null ? ProtocalWrap.packageType.RES : result;
    }

    public static final int REQ_FIELD_NUMBER = 2;
    /**
     * <code>optional .com.jq.seriliza.probuf.Req req = 2;</code>
     */
    public boolean hasReq() {
      return packCase_ == 2;
    }
    /**
     * <code>optional .com.jq.seriliza.probuf.Req req = 2;</code>
     */
    public ProtocalWrap.Req getReq() {
      if (packCase_ == 2) {
         return (ProtocalWrap.Req) pack_;
      }
      return ProtocalWrap.Req.getDefaultInstance();
    }
    /**
     * <code>optional .com.jq.seriliza.probuf.Req req = 2;</code>
     */
    public ProtocalWrap.ReqOrBuilder getReqOrBuilder() {
      if (packCase_ == 2) {
         return (ProtocalWrap.Req) pack_;
      }
      return ProtocalWrap.Req.getDefaultInstance();
    }

    public static final int RES_FIELD_NUMBER = 3;
    /**
     * <code>optional .com.jq.seriliza.probuf.Res res = 3;</code>
     */
    public boolean hasRes() {
      return packCase_ == 3;
    }
    /**
     * <code>optional .com.jq.seriliza.probuf.Res res = 3;</code>
     */
    public ProtocalWrap.Res getRes() {
      if (packCase_ == 3) {
         return (ProtocalWrap.Res) pack_;
      }
      return ProtocalWrap.Res.getDefaultInstance();
    }
    /**
     * <code>optional .com.jq.seriliza.probuf.Res res = 3;</code>
     */
    public ProtocalWrap.ResOrBuilder getResOrBuilder() {
      if (packCase_ == 3) {
         return (ProtocalWrap.Res) pack_;
      }
      return ProtocalWrap.Res.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_);
      }
      if (packCase_ == 2) {
        output.writeMessage(2, (ProtocalWrap.Req) pack_);
      }
      if (packCase_ == 3) {
        output.writeMessage(3, (ProtocalWrap.Res) pack_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (packCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (ProtocalWrap.Req) pack_);
      }
      if (packCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (ProtocalWrap.Res) pack_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ProtocalWrap.Message)) {
        return super.equals(obj);
      }
      ProtocalWrap.Message other = (ProtocalWrap.Message) obj;

      boolean result = true;
      result = result && (hasType() == other.hasType());
      if (hasType()) {
        result = result && type_ == other.type_;
      }
      result = result && getPackCase().equals(
          other.getPackCase());
      if (!result) return false;
      switch (packCase_) {
        case 2:
          result = result && getReq()
              .equals(other.getReq());
          break;
        case 3:
          result = result && getRes()
              .equals(other.getRes());
          break;
        case 0:
        default:
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
      }
      switch (packCase_) {
        case 2:
          hash = (37 * hash) + REQ_FIELD_NUMBER;
          hash = (53 * hash) + getReq().hashCode();
          break;
        case 3:
          hash = (37 * hash) + RES_FIELD_NUMBER;
          hash = (53 * hash) + getRes().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ProtocalWrap.Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtocalWrap.Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtocalWrap.Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtocalWrap.Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtocalWrap.Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtocalWrap.Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtocalWrap.Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ProtocalWrap.Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtocalWrap.Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtocalWrap.Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ProtocalWrap.Message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *MyMessage
     * </pre>
     *
     * Protobuf type {@code com.jq.seriliza.probuf.Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.jq.seriliza.probuf.Message)
        ProtocalWrap.MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtocalWrap.internal_static_com_jq_seriliza_probuf_Message_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtocalWrap.internal_static_com_jq_seriliza_probuf_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProtocalWrap.Message.class, ProtocalWrap.Message.Builder.class);
      }

      // Construct using com.jq.seriliza.probuf.ProtocalWrap.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 1;
        bitField0_ = (bitField0_ & ~0x00000001);
        packCase_ = 0;
        pack_ = null;
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtocalWrap.internal_static_com_jq_seriliza_probuf_Message_descriptor;
      }

      public ProtocalWrap.Message getDefaultInstanceForType() {
        return ProtocalWrap.Message.getDefaultInstance();
      }

      public ProtocalWrap.Message build() {
        ProtocalWrap.Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ProtocalWrap.Message buildPartial() {
        ProtocalWrap.Message result = new ProtocalWrap.Message(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (packCase_ == 2) {
          if (reqBuilder_ == null) {
            result.pack_ = pack_;
          } else {
            result.pack_ = reqBuilder_.build();
          }
        }
        if (packCase_ == 3) {
          if (resBuilder_ == null) {
            result.pack_ = pack_;
          } else {
            result.pack_ = resBuilder_.build();
          }
        }
        result.bitField0_ = to_bitField0_;
        result.packCase_ = packCase_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtocalWrap.Message) {
          return mergeFrom((ProtocalWrap.Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ProtocalWrap.Message other) {
        if (other == ProtocalWrap.Message.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        switch (other.getPackCase()) {
          case REQ: {
            mergeReq(other.getReq());
            break;
          }
          case RES: {
            mergeRes(other.getRes());
            break;
          }
          case PACK_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ProtocalWrap.Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ProtocalWrap.Message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int packCase_ = 0;
      private Object pack_;
      public PackCase
          getPackCase() {
        return PackCase.forNumber(
            packCase_);
      }

      public Builder clearPack() {
        packCase_ = 0;
        pack_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private int type_ = 1;
      /**
       * <pre>
       *data_type
       * </pre>
       *
       * <code>required .com.jq.seriliza.probuf.packageType type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       *data_type
       * </pre>
       *
       * <code>required .com.jq.seriliza.probuf.packageType type = 1;</code>
       */
      public ProtocalWrap.packageType getType() {
        ProtocalWrap.packageType result = ProtocalWrap.packageType.valueOf(type_);
        return result == null ? ProtocalWrap.packageType.RES : result;
      }
      /**
       * <pre>
       *data_type
       * </pre>
       *
       * <code>required .com.jq.seriliza.probuf.packageType type = 1;</code>
       */
      public Builder setType(ProtocalWrap.packageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *data_type
       * </pre>
       *
       * <code>required .com.jq.seriliza.probuf.packageType type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 1;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          Req, Req.Builder, ReqOrBuilder> reqBuilder_;
      /**
       * <code>optional .com.jq.seriliza.probuf.Req req = 2;</code>
       */
      public boolean hasReq() {
        return packCase_ == 2;
      }
      /**
       * <code>optional .com.jq.seriliza.probuf.Req req = 2;</code>
       */
      public ProtocalWrap.Req getReq() {
        if (reqBuilder_ == null) {
          if (packCase_ == 2) {
            return (ProtocalWrap.Req) pack_;
          }
          return ProtocalWrap.Req.getDefaultInstance();
        } else {
          if (packCase_ == 2) {
            return reqBuilder_.getMessage();
          }
          return ProtocalWrap.Req.getDefaultInstance();
        }
      }
      /**
       * <code>optional .com.jq.seriliza.probuf.Req req = 2;</code>
       */
      public Builder setReq(ProtocalWrap.Req value) {
        if (reqBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          pack_ = value;
          onChanged();
        } else {
          reqBuilder_.setMessage(value);
        }
        packCase_ = 2;
        return this;
      }
      /**
       * <code>optional .com.jq.seriliza.probuf.Req req = 2;</code>
       */
      public Builder setReq(
          ProtocalWrap.Req.Builder builderForValue) {
        if (reqBuilder_ == null) {
          pack_ = builderForValue.build();
          onChanged();
        } else {
          reqBuilder_.setMessage(builderForValue.build());
        }
        packCase_ = 2;
        return this;
      }
      /**
       * <code>optional .com.jq.seriliza.probuf.Req req = 2;</code>
       */
      public Builder mergeReq(ProtocalWrap.Req value) {
        if (reqBuilder_ == null) {
          if (packCase_ == 2 &&
              pack_ != ProtocalWrap.Req.getDefaultInstance()) {
            pack_ = ProtocalWrap.Req.newBuilder((ProtocalWrap.Req) pack_)
                .mergeFrom(value).buildPartial();
          } else {
            pack_ = value;
          }
          onChanged();
        } else {
          if (packCase_ == 2) {
            reqBuilder_.mergeFrom(value);
          }
          reqBuilder_.setMessage(value);
        }
        packCase_ = 2;
        return this;
      }
      /**
       * <code>optional .com.jq.seriliza.probuf.Req req = 2;</code>
       */
      public Builder clearReq() {
        if (reqBuilder_ == null) {
          if (packCase_ == 2) {
            packCase_ = 0;
            pack_ = null;
            onChanged();
          }
        } else {
          if (packCase_ == 2) {
            packCase_ = 0;
            pack_ = null;
          }
          reqBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .com.jq.seriliza.probuf.Req req = 2;</code>
       */
      public ProtocalWrap.Req.Builder getReqBuilder() {
        return getReqFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.jq.seriliza.probuf.Req req = 2;</code>
       */
      public ProtocalWrap.ReqOrBuilder getReqOrBuilder() {
        if ((packCase_ == 2) && (reqBuilder_ != null)) {
          return reqBuilder_.getMessageOrBuilder();
        } else {
          if (packCase_ == 2) {
            return (ProtocalWrap.Req) pack_;
          }
          return ProtocalWrap.Req.getDefaultInstance();
        }
      }
      /**
       * <code>optional .com.jq.seriliza.probuf.Req req = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Req, Req.Builder, ReqOrBuilder>
          getReqFieldBuilder() {
        if (reqBuilder_ == null) {
          if (!(packCase_ == 2)) {
            pack_ = ProtocalWrap.Req.getDefaultInstance();
          }
          reqBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Req, Req.Builder, ReqOrBuilder>(
                  (ProtocalWrap.Req) pack_,
                  getParentForChildren(),
                  isClean());
          pack_ = null;
        }
        packCase_ = 2;
        onChanged();;
        return reqBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          Res, Res.Builder, ResOrBuilder> resBuilder_;
      /**
       * <code>optional .com.jq.seriliza.probuf.Res res = 3;</code>
       */
      public boolean hasRes() {
        return packCase_ == 3;
      }
      /**
       * <code>optional .com.jq.seriliza.probuf.Res res = 3;</code>
       */
      public ProtocalWrap.Res getRes() {
        if (resBuilder_ == null) {
          if (packCase_ == 3) {
            return (ProtocalWrap.Res) pack_;
          }
          return ProtocalWrap.Res.getDefaultInstance();
        } else {
          if (packCase_ == 3) {
            return resBuilder_.getMessage();
          }
          return ProtocalWrap.Res.getDefaultInstance();
        }
      }
      /**
       * <code>optional .com.jq.seriliza.probuf.Res res = 3;</code>
       */
      public Builder setRes(ProtocalWrap.Res value) {
        if (resBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          pack_ = value;
          onChanged();
        } else {
          resBuilder_.setMessage(value);
        }
        packCase_ = 3;
        return this;
      }
      /**
       * <code>optional .com.jq.seriliza.probuf.Res res = 3;</code>
       */
      public Builder setRes(
          ProtocalWrap.Res.Builder builderForValue) {
        if (resBuilder_ == null) {
          pack_ = builderForValue.build();
          onChanged();
        } else {
          resBuilder_.setMessage(builderForValue.build());
        }
        packCase_ = 3;
        return this;
      }
      /**
       * <code>optional .com.jq.seriliza.probuf.Res res = 3;</code>
       */
      public Builder mergeRes(ProtocalWrap.Res value) {
        if (resBuilder_ == null) {
          if (packCase_ == 3 &&
              pack_ != ProtocalWrap.Res.getDefaultInstance()) {
            pack_ = ProtocalWrap.Res.newBuilder((ProtocalWrap.Res) pack_)
                .mergeFrom(value).buildPartial();
          } else {
            pack_ = value;
          }
          onChanged();
        } else {
          if (packCase_ == 3) {
            resBuilder_.mergeFrom(value);
          }
          resBuilder_.setMessage(value);
        }
        packCase_ = 3;
        return this;
      }
      /**
       * <code>optional .com.jq.seriliza.probuf.Res res = 3;</code>
       */
      public Builder clearRes() {
        if (resBuilder_ == null) {
          if (packCase_ == 3) {
            packCase_ = 0;
            pack_ = null;
            onChanged();
          }
        } else {
          if (packCase_ == 3) {
            packCase_ = 0;
            pack_ = null;
          }
          resBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .com.jq.seriliza.probuf.Res res = 3;</code>
       */
      public ProtocalWrap.Res.Builder getResBuilder() {
        return getResFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.jq.seriliza.probuf.Res res = 3;</code>
       */
      public ProtocalWrap.ResOrBuilder getResOrBuilder() {
        if ((packCase_ == 3) && (resBuilder_ != null)) {
          return resBuilder_.getMessageOrBuilder();
        } else {
          if (packCase_ == 3) {
            return (ProtocalWrap.Res) pack_;
          }
          return ProtocalWrap.Res.getDefaultInstance();
        }
      }
      /**
       * <code>optional .com.jq.seriliza.probuf.Res res = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Res, Res.Builder, ResOrBuilder>
          getResFieldBuilder() {
        if (resBuilder_ == null) {
          if (!(packCase_ == 3)) {
            pack_ = ProtocalWrap.Res.getDefaultInstance();
          }
          resBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Res, Res.Builder, ResOrBuilder>(
                  (ProtocalWrap.Res) pack_,
                  getParentForChildren(),
                  isClean());
          pack_ = null;
        }
        packCase_ = 3;
        onChanged();;
        return resBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.jq.seriliza.probuf.Message)
    }

    // @@protoc_insertion_point(class_scope:com.jq.seriliza.probuf.Message)
    private static final ProtocalWrap.Message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ProtocalWrap.Message();
    }

    public static ProtocalWrap.Message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<Message>
        PARSER = new com.google.protobuf.AbstractParser<Message>() {
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Message> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    public ProtocalWrap.Message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.jq.seriliza.probuf.Req)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string content = 1;</code>
     */
    boolean hasContent();
    /**
     * <code>optional string content = 1;</code>
     */
    String getContent();
    /**
     * <code>optional string content = 1;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();
  }
  /**
   * Protobuf type {@code com.jq.seriliza.probuf.Req}
   */
  public  static final class Req extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.jq.seriliza.probuf.Req)
      ReqOrBuilder {
    // Use Req.newBuilder() to construct.
    private Req(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Req() {
      content_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Req(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              content_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtocalWrap.internal_static_com_jq_seriliza_probuf_Req_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtocalWrap.internal_static_com_jq_seriliza_probuf_Req_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProtocalWrap.Req.class, ProtocalWrap.Req.Builder.class);
    }

    private int bitField0_;
    public static final int CONTENT_FIELD_NUMBER = 1;
    private volatile Object content_;
    /**
     * <code>optional string content = 1;</code>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string content = 1;</code>
     */
    public String getContent() {
      Object ref = content_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          content_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string content = 1;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, content_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, content_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ProtocalWrap.Req)) {
        return super.equals(obj);
      }
      ProtocalWrap.Req other = (ProtocalWrap.Req) obj;

      boolean result = true;
      result = result && (hasContent() == other.hasContent());
      if (hasContent()) {
        result = result && getContent()
            .equals(other.getContent());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasContent()) {
        hash = (37 * hash) + CONTENT_FIELD_NUMBER;
        hash = (53 * hash) + getContent().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ProtocalWrap.Req parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtocalWrap.Req parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtocalWrap.Req parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtocalWrap.Req parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtocalWrap.Req parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtocalWrap.Req parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtocalWrap.Req parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ProtocalWrap.Req parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtocalWrap.Req parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtocalWrap.Req parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ProtocalWrap.Req prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.jq.seriliza.probuf.Req}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.jq.seriliza.probuf.Req)
        ProtocalWrap.ReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtocalWrap.internal_static_com_jq_seriliza_probuf_Req_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtocalWrap.internal_static_com_jq_seriliza_probuf_Req_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProtocalWrap.Req.class, ProtocalWrap.Req.Builder.class);
      }

      // Construct using com.jq.seriliza.probuf.ProtocalWrap.Req.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        content_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtocalWrap.internal_static_com_jq_seriliza_probuf_Req_descriptor;
      }

      public ProtocalWrap.Req getDefaultInstanceForType() {
        return ProtocalWrap.Req.getDefaultInstance();
      }

      public ProtocalWrap.Req build() {
        ProtocalWrap.Req result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ProtocalWrap.Req buildPartial() {
        ProtocalWrap.Req result = new ProtocalWrap.Req(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.content_ = content_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtocalWrap.Req) {
          return mergeFrom((ProtocalWrap.Req)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ProtocalWrap.Req other) {
        if (other == ProtocalWrap.Req.getDefaultInstance()) return this;
        if (other.hasContent()) {
          bitField0_ |= 0x00000001;
          content_ = other.content_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ProtocalWrap.Req parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ProtocalWrap.Req) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object content_ = "";
      /**
       * <code>optional string content = 1;</code>
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string content = 1;</code>
       */
      public String getContent() {
        Object ref = content_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            content_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string content = 1;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string content = 1;</code>
       */
      public Builder setContent(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string content = 1;</code>
       */
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000001);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>optional string content = 1;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        content_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.jq.seriliza.probuf.Req)
    }

    // @@protoc_insertion_point(class_scope:com.jq.seriliza.probuf.Req)
    private static final ProtocalWrap.Req DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ProtocalWrap.Req();
    }

    public static ProtocalWrap.Req getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<Req>
        PARSER = new com.google.protobuf.AbstractParser<Req>() {
      public Req parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Req(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Req> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Req> getParserForType() {
      return PARSER;
    }

    public ProtocalWrap.Req getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.jq.seriliza.probuf.Res)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string content = 1;</code>
     */
    boolean hasContent();
    /**
     * <code>optional string content = 1;</code>
     */
    String getContent();
    /**
     * <code>optional string content = 1;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();
  }
  /**
   * Protobuf type {@code com.jq.seriliza.probuf.Res}
   */
  public  static final class Res extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.jq.seriliza.probuf.Res)
      ResOrBuilder {
    // Use Res.newBuilder() to construct.
    private Res(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Res() {
      content_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Res(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              content_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtocalWrap.internal_static_com_jq_seriliza_probuf_Res_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtocalWrap.internal_static_com_jq_seriliza_probuf_Res_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProtocalWrap.Res.class, ProtocalWrap.Res.Builder.class);
    }

    private int bitField0_;
    public static final int CONTENT_FIELD_NUMBER = 1;
    private volatile Object content_;
    /**
     * <code>optional string content = 1;</code>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string content = 1;</code>
     */
    public String getContent() {
      Object ref = content_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          content_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string content = 1;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, content_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, content_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ProtocalWrap.Res)) {
        return super.equals(obj);
      }
      ProtocalWrap.Res other = (ProtocalWrap.Res) obj;

      boolean result = true;
      result = result && (hasContent() == other.hasContent());
      if (hasContent()) {
        result = result && getContent()
            .equals(other.getContent());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasContent()) {
        hash = (37 * hash) + CONTENT_FIELD_NUMBER;
        hash = (53 * hash) + getContent().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ProtocalWrap.Res parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtocalWrap.Res parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtocalWrap.Res parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtocalWrap.Res parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtocalWrap.Res parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtocalWrap.Res parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtocalWrap.Res parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ProtocalWrap.Res parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtocalWrap.Res parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtocalWrap.Res parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ProtocalWrap.Res prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.jq.seriliza.probuf.Res}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.jq.seriliza.probuf.Res)
        ProtocalWrap.ResOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtocalWrap.internal_static_com_jq_seriliza_probuf_Res_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtocalWrap.internal_static_com_jq_seriliza_probuf_Res_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProtocalWrap.Res.class, ProtocalWrap.Res.Builder.class);
      }

      // Construct using com.jq.seriliza.probuf.ProtocalWrap.Res.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        content_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtocalWrap.internal_static_com_jq_seriliza_probuf_Res_descriptor;
      }

      public ProtocalWrap.Res getDefaultInstanceForType() {
        return ProtocalWrap.Res.getDefaultInstance();
      }

      public ProtocalWrap.Res build() {
        ProtocalWrap.Res result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ProtocalWrap.Res buildPartial() {
        ProtocalWrap.Res result = new ProtocalWrap.Res(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.content_ = content_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtocalWrap.Res) {
          return mergeFrom((ProtocalWrap.Res)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ProtocalWrap.Res other) {
        if (other == ProtocalWrap.Res.getDefaultInstance()) return this;
        if (other.hasContent()) {
          bitField0_ |= 0x00000001;
          content_ = other.content_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ProtocalWrap.Res parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ProtocalWrap.Res) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object content_ = "";
      /**
       * <code>optional string content = 1;</code>
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string content = 1;</code>
       */
      public String getContent() {
        Object ref = content_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            content_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string content = 1;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string content = 1;</code>
       */
      public Builder setContent(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string content = 1;</code>
       */
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000001);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>optional string content = 1;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        content_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.jq.seriliza.probuf.Res)
    }

    // @@protoc_insertion_point(class_scope:com.jq.seriliza.probuf.Res)
    private static final ProtocalWrap.Res DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ProtocalWrap.Res();
    }

    public static ProtocalWrap.Res getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<Res>
        PARSER = new com.google.protobuf.AbstractParser<Res>() {
      public Res parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Res(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Res> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Res> getParserForType() {
      return PARSER;
    }

    public ProtocalWrap.Res getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_jq_seriliza_probuf_Message_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_jq_seriliza_probuf_Message_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_jq_seriliza_probuf_Req_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_jq_seriliza_probuf_Req_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_jq_seriliza_probuf_Res_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_jq_seriliza_probuf_Res_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016protocol.proto\022\026com.jq.seriliza.probuf" +
      "\"\234\001\n\007Message\0221\n\004type\030\001 \002(\0162#.com.jq.seri" +
      "liza.probuf.packageType\022*\n\003req\030\002 \001(\0132\033.c" +
      "om.jq.seriliza.probuf.ReqH\000\022*\n\003res\030\003 \001(\013" +
      "2\033.com.jq.seriliza.probuf.ResH\000B\006\n\004pack\"" +
      "\026\n\003Req\022\017\n\007content\030\001 \001(\t\"\026\n\003Res\022\017\n\007conten" +
      "t\030\001 \001(\t*\037\n\013packageType\022\007\n\003RES\020\001\022\007\n\003REQ\020\002" +
      "B&\n\026com.jq.seriliza.probufB\014ProtocalWrap"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_jq_seriliza_probuf_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_jq_seriliza_probuf_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_jq_seriliza_probuf_Message_descriptor,
        new String[] { "Type", "Req", "Res", "Pack", });
    internal_static_com_jq_seriliza_probuf_Req_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_jq_seriliza_probuf_Req_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_jq_seriliza_probuf_Req_descriptor,
        new String[] { "Content", });
    internal_static_com_jq_seriliza_probuf_Res_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_jq_seriliza_probuf_Res_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_jq_seriliza_probuf_Res_descriptor,
        new String[] { "Content", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
